### ISSUE TITLE
Create multi-select dropdown for Verification Status so that Captures view total counts are correct

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#114]
Total number of filtered not showing (only displaying total number of all trees) see screenshot
![Screenshot 2021-06-11 at 10 48 43](https://user-images.githubusercontent.com/3283800/121650942-c6937f80-caa2-11eb-92ae-9c7958b7fcd4.png)

It should be around 2000 captures in this case. 
We could also rename that entire section to captures.

**Comment by thejoshcooter** [comment]
I have been unable to replicate this bug. On my end I am seeing the correct number of captures displayed for each result via `captureCount` prop.

It looks like @nmcharlton did a refactor some time ago where the section was renamed to captures that may have resolved the issue.

**Comment by nmcharlton** [comment]
@thejoshcooter You're right – I believe this was largely fixed in the refactor.

There is still a minor discrepancy between the initial count and the initial list of captures. The former includes rejected captures but not the latter does not.
By default, there are no filters applied on this page, so with the current set of filters, rejected captures should be included.
However, this seems counter-intuitive for users. Instead, I think we should have checkboxes for each of the _Verification Status_ values with _Approved_ checked by default and perhaps _Awaiting verification_ too.

Given how much this tool has fallen behind the _Verify_ tool, we need to consider the use cases for the _Captures_ tool and which default filter makes the most sense.

As a quick fix for this issue, let's set _Verification Status_ to _Approved_ by default.

**Comment by chromium-52** [comment]
@nmcharlton Is anyone working on this issue?

**Comment by nmcharlton** [comment]
> @nmcharlton Is anyone currently working on this issue?

@chromium-52 I don't think so.

**Comment by chromium-52** [comment]
> @chromium-52 I don't think so.

@nmcharlton Then could I try this one? Also, just to clarify, we're replacing the dropdown menu for Verification Status with checkboxes and selecting just the Approved option by default, correct?

**Comment by nmcharlton** [comment]
@chromium-52 Go for it 😀

For consistency, it may be best to use a multi-select dropdown, but I'm open to proposed designs.

Having spoken to @sebastiangaertner I think _Approved_ and _Awaiting Verification_ should be checked by default.

Be aware that we want to consolidate the Verify and Captures filter components into one responsive component. That will reduce the amount of duplication needed when we want to add a field to the filters. See #51 for details.

**Comment by chromium-52** [comment]
@nmcharlton Is there a way to filter captures based on more than one verification status? Since the current design is a single-choice dropdown menu, users can choose only one out of the four options (_All_, __Approved_, _Awaiting Verification_, or _Rejected_). However, if this were to be replaced by a multi-select dropdown menu, then users can now choose a combination of verification statuses (e.g. _Approved_ and _Awaiting Verification_). How can I set the fields of FilterModel such that captures that match any of the chosen verification statuses will be retrieved? Thank you!

**Comment by nmcharlton** [comment]
@chromium-52 Not at the moment. Each of the verification statuses maps to a unique combination of `approved` and `active` in the filter model.

The filter model will need to be modified to account for multiple combinations of these two fields, joined in the loopback query with an `or` statement.

I'd be tempted to make  the verification status values into the model (as an array) and only set the corresponding `active`/`approved` values in the `getWhereObj()` function. At some point in the future, these status values will replace the boolean combination in the database.

Statuses are mapped as follows:

- Approved: `active===true && approved===true`
- Awaiting verification: `active===true && approved===false`
- Rejected: `active===false && approved===false`

**Comment by nmcharlton** [comment]
For info, @tranquanghuy0801 is working on the related issue #51. There may be some crossover here with updates to the filters.

**Comment by chromium-52** [comment]
Ah okay! So if I understand it correctly, would I remove both `approved` and `active` fields in the filter model and replace them with a `status` field that will be an array and hold a combination of _Approved_, _Awaiting Verification_, and _Rejected_ values (depending on what the user chooses)? Also, if the user applies the filter with none of the verification statuses selected, should it prompt some sort of an alert message or just retrieve 0 captures?

**Comment by nmcharlton** [comment]
@chromium-52 That's right. I'd suggest calling it `verificationStatus` for consistency.

If no option is selected, the default should be to include all captures.

**Comment by tranquanghuy0801** [comment]
@nmcharlton  Can I take on this issue?

**Comment by tranquanghuy0801** [comment]
@nmcharlton 
I need your help a bit in this case.

From the dicussion you guys made above, we will be using the multi-select dropdown menu for` Verification Status`, and therefore  either `active` or `approve` field will have more than one value ( `active = false` or `active = true`)

I have read the where filter or condition in Loopback in this link https://loopback.io/doc/en/lb2/Where-filter.html#and--or
But I am still not clear how can I implement this in function `getWhereObj(`) of filter to make this work. Could I assign the `active` field an array `[true, false]`? I reckon this is not the right way. 

Thanks

**Comment by nmcharlton** [comment]
Hi @tranquanghuy0801. Can I suggest you ask this in #admin_panel_chat in Slack?
Looks like a good problem for a fellow developer in the team to help out with.
