### ISSUE TITLE
Unable to edit Species

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#117]
Trying to add description to an existing species does not work.

**Comment by nmcharlton** [comment]
Editing an existing species gives the following message:

![Screenshot 2021-06-16 at 20 17 37](https://user-images.githubusercontent.com/5558838/122279435-f0ec9f00-cedf-11eb-926d-dc8c9d05fd63.png)

This suggests that either the check for duplicate species name is in the wrong place, or we're calling the _create species_ function instead of _update species_.

**Comment by tranquanghuy0801** [comment]
Hi, can I work on this issue?
