### ISSUE TITLE
Critical: Can not filter by Organization id when logged in with user role

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#161]
See attached. This is a user under freetown policy in "public.admin_role" linking organization_id = 178  "public.entity_relationship" with the organizations_ids 838, 183, 839, 184, 179, 840, 836, 841, 842, 837, 182.
When logging in under a Freetown user and filtering by organization_id the filter does not work. see image attached. 
![Screenshot 2021-09-20 at 09 37 01](https://user-images.githubusercontent.com/3283800/133964788-b765c1b6-cf8b-4cc9-a084-30d623af8579.png)

**Comment by Mloweedgar** [comment]
I would like to work  on this Issue. Since I'm kind new to the code-base can you help me fill the template below so that I can be able to reproduce and fix the bug :point_down: 

## Description


## How to reproduce

-  
- 

*Expected Result*


*Current Result*



- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>


(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
