### ISSUE TITLE
The menu UI got a bit displaced because of the width

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#198]
<img width="1440" alt="Screen Shot 2021-11-15 at 2 06 07 PM" src="https://user-images.githubusercontent.com/5744708/141730992-be025008-bac0-48e4-94ec-60a546667164.png">

**Comment by nmcharlton** [comment]
That's interesting, is that Chrome? It renders OK for me (on Windows):

![image](https://user-images.githubusercontent.com/5558838/141860675-baf44968-c79c-4de6-9fdb-50869154b8fa.png)

**Comment by nmcharlton** [comment]
On a related note, we need to fix the width of the menu in other tools that display a fixed menu (Species, User Manager, Account).

**Comment by Tiaraha-funny** [comment]
@nmcharlton -We are going to fix this issue so we want some clarifications. We think we can solve it in these ways but we don't  know which option should be the best for it.
- We set fix-width to the menu so when we resized the page, the width of the menu doesn't shrink.
OR
- We set word-wrap for the content menu (links) so that when we resize the page, the width of the menu shrinks but the content (links) wraps down.
OR
- Set fix-width to the content menu (links) so when we resize it, it doesn't wrap but shrink (can be very small), and the width menu can shrink as well.

**Comment by nmcharlton** [comment]
@Tiaraha-funny Thanks for picking this up!
My preference is the first option – set a fixed width on the menu that is wide enough to accommodate all of the menu items and is consistent across all tools.

We don't currently fully support a responsive design, but if/when we do, the menu would become a drawer (popover) when we reach a small screen breakpoint.
