### ISSUE TITLE
Round up to whole numbers on all statistic cards

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-client#250]
This statistic card shows tenths, hundredths, and thousands place after the decimal.  Instead round up to a whole number.   This can be fixed on the API side as well.

![image](https://user-images.githubusercontent.com/364622/147166487-6d852f8a-a0f5-45a6-ad63-fb650b8dff16.png)

**Comment by sunnyjain15699** [comment]
Hi! I would like to work on this issue. Can you guide me through it ?

**Comment by dadiorchen** [comment]
Yes, please read the `readme` to get started, installing and running the project locally, then try to reproduce the problem, and fix it. 

If you want to join our slack community, please give me you email address, then I can invite you

**Comment by dadiorchen** [comment]
@arcadioramos  is this the same case as your last PR? using countToLocaleString? If it's true, I think it would be better you make a quick PR on this so we can solve this issue soon.

**Comment by dadiorchen** [comment]
https://github.com/Greenstand/treetracker-admin-client/issues/251

**Comment by arcadioramos** [comment]
Hi @dadiorchen , it is a different case because here we have that the numbers have decimal and here what I can see is that they want to remove the decimal and to add +1 if tur number has a decimal to round the number up, I think I can solve it quick but give me until tomorrow because I'm kinda busy at the moment
