### ISSUE TITLE
Capture Matching: Create context for shared state

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#46]
We should create a ~~Rematch model~~ React context to maintain the state of the Capture Matching tool and share that state amongst the various components of the tool without the need to pass props down through the hierarchy.

**Comment by nmcharlton** [comment]
Rematch is being removed from the project and shared state will move to React Context instead.

**Comment by dadiorchen** [comment]
@nmcharlton in my opinion, I think for some cases, it's good to leave some states in the component, rather than strictly move to context, I tend to just use context when necessary, for cases where we need to pass on props, callbacks in deep, context and too much hierarchy of the component tree brings the cost to maintain code
