### ISSUE TITLE
Earnings page->Detail panel: missing `payment method`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-client#507]
We should display the payment method, and `payment_confirmation_id`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/158291876-e12686ef-0182-4d5e-b501-3aa74e2d4de0.png">

**Comment by dadiorchen** [comment]
@Mloweedgar do you think this is a valid issue? We are missing the `payment method`, in this case, I populated the log form and submit, then I can not find the `payment method` in the detail panel.

**Comment by Mloweedgar** [comment]
@dadiorchen I have  looked into this, `payment_method` was not included in the earnings detail UI design(see https://www.figma.com/proto/G4Kl9fzLRgnk0SaeTne1Mc/Admin-Panel---Master?node-id=6453%3A11276&scaling=min-zoom&page-id=6378%3A4149), but It is possible to add it as well and make it show only when Earning is paid since it will always be `null` for calculated earnings.

**Comment by dadiorchen** [comment]
I think we should give the user the place to check the payment method and confirmation id.

**Comment by dadiorchen** [comment]
@Mloweedgar I will take this
