### ISSUE TITLE
Device info, Organization not showing in Admin Panel

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#523]
![Screenshot 2022-03-12 at 07 35 59](https://user-images.githubusercontent.com/3283800/158005082-b33218b3-aa19-43db-b2c2-1d846ed28a40.png)

**Comment by nmcharlton** [comment]
We now have a registration date and a country showing for this grower, but the `organization` (`public.planter` table) and `device_identifier` (`public.planter_registration` table) fields are blank in the database.
Are we still populating those?

**Comment by ZavenArra** [comment]
We should read this data from the field_data schema now.  

An individual grower account can have multiple organizations - this is because a grower account has multiple sessions and each session can have an organization that has been selected.

And individual grower has multiple devices, but note that in the field_data schema these are captures as 'device_configuration' which means the same device will have separate configurations over time.

For each grower, we would like show a session history, or at least start with showing all organization and devices used.

**Comment by nmcharlton** [comment]
This change depends on porting the Growers tool across to treetracker-api so that we have access to the new grower uuid to link to the field_data.

@gwynndp One for the list.
