### ISSUE TITLE
Disable Grower tooltips for placeholder cards

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#701]
When a user opens a new page in the Growers tool, they see a set of grey placeholder cards while the data loads.
Currently, if they hover over one of these, they see an empty tooltip.

We don't need this tooltip – one option is to disable pointer events for the placeholder cards in CSS.
<img width="517" alt="Screenshot 2022-06-19 at 14 02 41" src="https://user-images.githubusercontent.com/5558838/174482327-7a8b5b37-2d43-4b7c-92f7-ecc8b874d429.png">

**Comment by kvaithin** [comment]
Hi, wanted to attempt a fix for this issue. 
How can I get the name for this organisation to join the Slack channel `admin_panel_chat`? 
Or could I get a link to join the channel.

Looking to obtain the login credentials from there.

**Comment by nmcharlton** [comment]
Hi @kvaithin, that's great.
Follow this link to join our Slack: https://join.slack.com/t/greenstand/shared_invite/zt-1awc8lf2f-Gk5BcEIqXIUaq7_leFhg_w

**Comment by nmcharlton** [comment]
Hey @kvaithin. Have you been able to make any progress on this issue? Please ask if you need any assistance.

**Comment by kvaithin** [comment]
@nmcharlton Apologies. Was looking into it. 

Under `src/components/Growers/Growers.styles.js` there is already styling for placeholder where it is indicating
`pointerEvents: 'none',`. 

But this has no effect. Whereas if I got up 2 levels and add `pointerEvents: 'none'`, it works. 

In code, this is fixable by adding the following under `src/components/Growers/Growers.js`.

```
        <Box
            className={grower.placeholder && classes.disablePointerEvent} <--- This line is new.
        >
          <Grower
            onClick={() => handleGrowerClick(grower)}
            key={`${i} + ${grower.id}`}
            grower={grower}
            placeholder={grower.placeholder}
          />
        </Box>
```

Existing placeHolder css class has other styling which has side effects when I try to reuse it.
Thus added `disablePointerEvent` css class which only has `pointerEvents: 'none',`.

Wanted to get some thoughts around this solution. And also since placeHolder's pointer-event styling seems to have no effect, 
would it be worth removing that.

**Comment by nmcharlton** [comment]
@kvaithin That sounds good thanks to me

**Comment by kidwizard42** [comment]
@nmcharlton can this be assigned to me? I have a  PR for this. I also noticed that if you click the placeholder cards there is a pop up and removed that too.
