### ISSUE TITLE
GENDER. One of the most important requirement by Freetown is to show gender percentage in planters

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-client#703]
In order to show this we need to have 3 genders. male/female/neutral. This is a critical requirement!

**Comment by gwynndp** [comment]
Ultimately we will want to have the UX for assigning gender become a part of the Stakeholder tool, but until we have a way of verifying growers as Person Stakeholders there won't be a way to tie the gender data to grower accounts. 

Temporarily we can add a field for gender to the planter table in the old API.  Then it can be related to growers in the new api, and ultimately to the Stakeholders.

To display the data we can add a report card to the Dashboard.  This sum will need to exclude growers who haven't made any captures and will be based on planter_id/wallet so that they are only counting unique individuals.

**Todo:**
- updating the Airflow event to get the gender report data & create a gender report
- creating a report card to display the data
- updating the production database (will need permissions for this step)
