### ISSUE TITLE
Captures: Filtering by multiple Grower IDs gives incorrect results

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#766]
## Steps to reproduce
1. Open Captures tool
2. Enter two Grower IDs (select from the Captures list) separated by a comma in the _Grower ID_ filter and press _Apply_
3. Captures from other growers are included in the results.

<img width="1552" alt="Screenshot 2022-07-30 at 21 12 06" src="https://user-images.githubusercontent.com/5558838/181994776-ded46afe-b7b8-4b69-b16a-5502767c24f7.png">

**Comment by rutvij2811** [comment]
Query String Image with multiple IDs:
![image](https://user-images.githubusercontent.com/13500309/183307026-2d5b46d7-82bb-461d-896b-a8e9bb83c284.png)
Query String Image with single ID:
![image](https://user-images.githubusercontent.com/13500309/183307075-5b0fda0e-b147-4d95-8dea-cc4fd0c68d7c.png)

From the initial looks, the issue lies with the "OR" condition put all together.
When there are multiple ids queried, it also put the "active" filters in the same "OR" condition, hence we see all the results regardless of the grower ID used.
Whereas when there is a single ID, we can see that the "plantID" is not clubbed within the "OR" condition and I assume that internally an "AND" clause separates the filters.

Possible Solution:
I think if somehow we can have a separate "OR" scope for the GrowerID, then the issue can be resolved.
I am not sure how to proceed with adding that as I am extremely new to this project and haven't gone through the codebase yet.

I would like to work on this with some guidance on the query string parameter part.

**Comment by rutvij2811** [comment]
@nmcharlton ,
Could you please assign this issue to me? I think now  I am confident about my assumption and I found out where the changes need to be made. Some modifications are required in the Filter.js file in the models directory to handle the "and" and "or" conditions.

**Comment by nmcharlton** [comment]
Thanks @rutvij2811. That sounds right.
The API query uses LoopBack 4. Check the docs for the spec.
