### ISSUE TITLE
Regions: Allow users to download geojson shapefiles

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#777]
Add a _download_ button to records in the Regions table.
The _download_ icon can be inserted before the _edit_ and _delete_ icons.

The endpoint `REGION_API/region/:region_id/shape` returns a downloadable geojson file.

**Comment by rohanshankar** [comment]
This would be my first time contributing to an open sourced project. Mind if I give it a try?

**Comment by nmcharlton** [comment]
@rohanshankar It's all yours!

**Comment by rohanshankar** [comment]
> 

Is there any documentation on that endpoint?

**Comment by nmcharlton** [comment]
See https://github.com/Greenstand/treetracker-regions-api/blob/b41ccdcd6403b70e339fd43208c04f7a899e9916/docs/api/spec/region-api.yaml

**Comment by nmcharlton** [comment]
Hi @rohanshankar. Have you been able to make any progress on this issue?
Let me know if you have any questions.

**Comment by andres039** [comment]
Hi @nmcharlton and @rohanshankar, I found this particular issue very interesting since I've never worked with downloadable files. I think I have a working solution, but I was wondering if the structure of my code is right and meets the requirements, I can do a pull request if you guys like to look at it and maybe give some suggestions ( if @rohanshankar has time we could even pair-program on it). Thanks guys!
