### ISSUE TITLE
Captures: Capture Details not shown on capture click

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#862]
_Version: 1.108.0_

## Steps to Reproduce
1. Open Captures tool
2. Click any row in the table
3. Nothing happens

## Expected Behaviour
Capture Detail dialog opens and shows details of the selected capture

**Comment by tranquanghuy0801** [comment]
The API call for capture detail has been updated in this commit https://github.com/Greenstand/treetracker-admin-client/commit/5530aef7e704be7764ee217e8a1d5d554a5781f3?diff=split#diff-18fa940aba496624830324f6c11fd3ddc739fa923ac995b85e83e0f0e5794bb0

Maybe this issue occurs because Admin API has not been updated?
