### ISSUE TITLE
Filter date selection: Cannot move forward

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-client#94]
The forward button on the date selector used in filters on the _Verify_ and _Trees_ pages is permanently disabled, meaning you can't navigate to the next month if you go back.
Instead, you need to close the date selector and reopen it.

https://user-images.githubusercontent.com/5558838/119395353-4a8bf000-bccb-11eb-9ed6-e6043b200caf.mov

**Comment by panzaverdeok** [comment]
Hi @nmcharlton 
I'm working in this issue.

I'll keeping you to the advance.

Regards.

**Comment by panzaverdeok** [comment]
Hey @nmcharlton !

I think that was solve issue. I did some test into local enviroment, these tests was a  ok. However, in relation to I have readed, think must pull on my git personal branch, do test and finally merge the solution into production enviroment. Please, could you says me how I must continue?

The issue was into FilterTop.js component, KeyboardDatePicker, minDate and maxDate parameters.
I will document complete the issue and solution next days.

Regards.

**Comment by nmcharlton** [comment]
@panzaverdeok You need to push your feature branch to your origin (`git push origin <branch-name>`) and [create a pull request in GitHub](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) from your local fork into `Greenstand/treetracker-admin-client: master`.

Once you have a pull request open, I can review your changes and merge them into the Greenstand repo.
If there are any conflicts raised in the pull request, we will need to resolve them before merging.

Let me know if you need any help with this.
